updates.ignore = [
  # com.datastax.cassandra:cassandra-driver-core:4.0.0 is a bogus artefact, the real v4 driver
  # has different groupId
  #
  # TODO: remove when driver 3 support dropped
  {groupId = "com.datastax.cassandra", artifactId = "cassandra-driver-core"},
  # jffi has to be compatible with the driver version
  # TODO: remove when driver 3 support dropped
  {groupId = "com.github.jnr", artifactId = "jffi"}
]
